version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
    container_name: app
    working_dir: ${WORKING_DIR}
    environment:
      APP_ENV: local
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./src/:${WORKING_DIR}
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # comment out this will disable xdebug
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf # mapping supervisord.conf
    networks:
      - app-network

  webserver:
    platform: linux/amd64
    image: nginx:alpine
    container_name: webserver
    working_dir: ${WORKING_DIR}
    depends_on:
      - app
    ports:
      - ${WORKSPACE_PORT}:80
      - ${WORKSPACE_PORT_SSL}:443
    volumes:
      - ./src/:${WORKING_DIR}
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    # platform: linux/x86_64
    # image: mysql:5.7
    image: mariadb:10.5.8
    container_name: db
    environment:
      MYSQL_DATABASE: "${DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
        - ${DB_PORT}:3306
    volumes:
      - ./docker/db/dbdata:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
